# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
darklua = "Stefanuk12/darklua@0.17.4"
lune = "lune-org/lune@0.9.3"
pcmp = "Proton-Utilities/ProCMP@2.1.0"